### ISSUE TITLE
Port to GitHub Actions

### ISSUE THREAD

**Issue by mastercoms** [GlowstoneMC/Linkstone#8]
We need to get Azure build and release pipelines working so deploys to our repo can work. Then, things like Glowstone can depend on Linkstone (https://github.com/GlowstoneMC/Glowstone/pull/952)

**Comment by Pr0methean** [comment]
This looks relevant: https://stackoverflow.com/questions/47920305/can-not-set-org-eclipse-aether-spi-log-logger-with-custom-maven-plugin

**Comment by mastercoms** [comment]
Changed issue to reflect that we now use Azure Pipelines.

**Comment by mastercoms** [comment]
CI building on GitHub Actions since b214df97bd9d3dcbae2ce09b48d72e8e8ab82851.
